config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  post 'update', to: 'static_pages#update'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'git_loader'

  def home
    @content = ''
  end

  def update
    GitLoader.load
    flash[:notice] = 'loaded'
    flash[:danger] = GitLoader.get_hash_for_file('config.ru')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_class_for_type(type)
    if %w(alert error).include?(type)
      'alert-danger'
    elsif %w(alert error).include?(type)
      'alert-success'
    elsif 'notice' == type
      'alert-info'
    elsif 'timedout' == type
      nil
    else
      "alert-#{type}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/_flashes.html.erb
<div class="flashes container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="alert alert-info" id="runtime_flash" style="display:none;">
        <span></span>
      </div>
      <% flash.each do |key, value| %>
          <% klass = alert_class_for_type(key) %>
          <% if klass %>
              <%= content_tag(:div, class: "alert alert-dismissible #{klass} fade in") do %>
                  <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                  <%= value %>
              <% end %>
          <% end %>
      <% end %>
      <% flash.clear %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTest</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'flashes' %>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<%= link_to 'Update', update_path, method: :post %>
<%= @content %>